version: '3.8'

services:
  elb:
    container_name: elb
    image: haproxy:lts-bookworm
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - nilapi01
      - nilapi02
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "336MB"

  surreal_db:
    container_name: surreal_db
    image: surrealdb/surrealdb:v1.2.0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    command:
      - start
      - --user=root
      - --pass=root
      - file:/data/transactions_machine.db
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "150MB"

  nilapi01:
    container_name: nilapi01
    image: nilferreira/rinha-2024-q1:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_URL: 0.0.0.0:8080
      DB_HOST: surreal_db:8000
      DB_NAMESPACE: rinha
      DB_NAME: transactions_machine
      DB_USER: root
      DB_PASS: root
    depends_on:
      - surreal_db
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "32MB"

  nilapi02:
    container_name: nilapi02
    image: nilferreira/rinha-2024-q1:latest
    ports:
      - "8081:8081"
    environment:
      SERVER_URL: 0.0.0.0:8081
      DB_HOST: surreal_db:8000
      DB_NAMESPACE: rinha
      DB_NAME: transactions_machine
      DB_USER: root
      DB_PASS: root
    depends_on:
      - surreal_db
      - nilapi01
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "32MB"

networks:
  default:
    driver: bridge