version: '3.8'

services:
  elb:
    container_name: elb
    image: haproxy:lts-bookworm
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - nilapi01
      - nilapi02
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "136MB"

  postgres:
    container_name: postgres
    image: postgres:16.2-bookworm
    ports:
      - "5432:5432"
    volumes:
      - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "374MB"

  nilapi01:
    container_name: nilapi01
    image: nilferreira/rinha-2024-q1:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_URL: 0.0.0.0:8080
      DB_HOST: postgres:5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  nilapi02:
    container_name: nilapi02
    image: nilferreira/rinha-2024-q1:latest
    ports:
      - "8081:8081"
    environment:
      SERVER_URL: 0.0.0.0:8081
      DB_HOST: postgres:5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

networks:
  default:
    driver: bridge